import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Result from "../components/Result";
import styles from "../styles/Home.module.css";
import requests from "../utils/requests";

//https://api.themoviedb.org/3/movie/550?api_key=3c36d72cfe5e8e3361189984dab1a575
// npm i react-flip-move

export default function Home(props) {
  console.log(props);
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Let Hulu 2.0</h1>

      {/* header */}
      <Header />

      {/* nav */}
      <Nav />

      {/* result */}
      <Result results={props.results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  // console.log(context);
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((response) => response.json());

  console.log(request);

  return {
    props: {
      results: request.results,
    },
  };
}
